apiVersion: v1
kind: Config
clusters:
  - cluster:
      certificate-authority: $CA_DATA_PATH
      server: $SERVER_ADDRESS
    name: default-kube-proxy
contexts:
  - context:
      cluster: default-kube-proxy
      user: default-kube-proxy
    name: default-kube-proxy
preferences: {}
users:
  - name: default-kube-proxy
    user:
      client-certificate: $CLIENT_CERTIFICATE_PATH
      client-key: $CLIENT_KEY_PATH
current-context: default-kube-proxy