apiVersion: v1
kind: Config
clusters:
  - cluster:
      certificate-authority: $CA_DATA_PATH
      server: $SERVER_ADDRESS
    name: default-kubelet
contexts:
  - context:
      cluster: default-kubelet
      user: default-kubelet
    name: default-kubelet
preferences: {}
users:
  - name: default-kubelet
    user:
      client-certificate: $CLIENT_CERTIFICATE_PATH
      client-key: $CLIENT_KEY_PATH
current-context: default-kubelet