kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  webhook:
    enabled: true
  x509:
    clientCAFile: $CA_DATA_PATH
containerRuntimeEndpoint: "unix:///var/run/containerd/containerd.sock"
cgroupDriver: systemd
tlsCertFile: $CLIENT_CERTIFICATE_PATH
tlsPrivateKeyFile: $CLIENT_KEY_PATH
address: $ADDRESS
port: $PORT
clusterDNS: [$CLUSTER_DNS]
clusterDomain: "cluster.local"