apiVersion: v1
kind: Config
clusters:
  - cluster:
      certificate-authority-data: $CA_DATA
      server: $SERVER_ADDRESS
    name: default-scheduler
contexts:
  - context:
      cluster: default-scheduler
      user: default-scheduler
    name: default-scheduler
preferences: {}
users:
  - name: default-scheduler
    user:
      client-certificate-data: $CLIENT_CERTIFICATE
      client-key-data: $CLIENT_KEY
current-context: default-scheduler