apiVersion: v1
kind: Config
clusters:
  - cluster:
      certificate-authority-data: $CA_DATA
      server: $SERVER_ADDRESS
    name: default-controller-manager
contexts:
  - context:
      cluster: default-controller-manager
      user: default-controller-manager
    name: default-controller-manager
preferences: {}
users:
  - name: default-controller-manager
    user:
      client-certificate-data: $CLIENT_CERTIFICATE
      client-key-data: $CLIENT_KEY
current-context: default-controller-manager