apiVersion: v1
kind: Config
clusters:
  - cluster:
      certificate-authority-data: $CA_DATA
      server: $SERVER_ADDRESS
    name: default-coredns
contexts:
  - context:
      cluster: default-coredns
      user: default-coredns
    name: default-coredns
preferences: {}
users:
  - name: default-coredns
    user:
      client-certificate-data: $CLIENT_CERTIFICATE
      client-key-data: $CLIENT_KEY
current-context: default-coredns