apiVersion: v1
kind: Config
clusters:
  - cluster:
      certificate-authority: $CA_DATA_PATH
      server: $SERVER_ADDRESS
    name: metal-cluster
contexts:
  - context:
      cluster: metal-cluster
      user: metal-user
    name: metal-context
preferences: {}
users:
  - name: metal-user
    user:
      client-certificate: $CLIENT_CERTIFICATE_PATH
      client-key: $CLIENT_KEY_PATH
current-context: metal-context